 version: '2'
 services:
   db:
     image: postgres
   rabbit:
     image: rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=chuser
       - RABBITMQ_DEFAULT_PASS=chpass
   web:
     build: .
     image: computationalhealthcare:latest
     command: bash -c "git pull && fab start_server_container"
     ports:
       - "8888:8888"
       - "8111:8000"
     depends_on:
       - db
       - rabbit
